CRUD_School294/Models/Teachers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_School294.Models
{
    public class Teachers
    {
        [Key]
        public int teacherId { get; set; }
        [Required]
        [Display(Name = "Teacher's Surname")]
        public string teacherSurname { get; set; }
        [Required]
        [Display(Name = "Teacher's Name")]
        public string teacherName { get; set; }
        [Required]
        [Display(Name = "Teacher's Date Of Birth")]
        public DateTime teacherDob { get; set; }
        [Required]
        [Display(Name = "Teacher Contact")]
        public string teacherContacts { get; set; }
        [Required]
        [Display(Name = "Teacher Contact2")]
        public string studentContact2 { get; set; }
    }
}

CRUD_School294/Controllers/StudentsController.cs
using CRUD_School294.Data;
using CRUD_School294.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_School294.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public StudentsController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GetAll from Students
        public IActionResult Index(string searchString)
        {
            var students = _db.Students.ToList();
            ViewData["CurrentFilter"] = searchString;
            
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(x => x.studentName.Contains(searchString) || x.studentSurname.Contains(searchString)).ToList();
            }
            return View(students);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Students students)
        {
            if (ModelState.IsValid)
            {
                _db.Students.Add(students);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(students);
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _db.Students.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Students.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Edit student record
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Students.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult EditStudent(Students students)
        {
            if (students == null)
            {
                return NotFound();
            }
            _db.Students.Update(students);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CRUD_School294/Controllers/TeachersController.cs
using CRUD_School294.Data;
using CRUD_School294.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_School294.Controllers
{
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TeachersController(ApplicationDbContext dbContext)
        {
            _db = dbContext;
        }

        public IActionResult Index(string searchString, string sortOrder, int pg=1)
        {
            const int pageSize = 10;

            if (pg < 1)
            {
                pg = 1;
            }

            int recsCount = _db.Teachers.Count();
            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;
            var teachers = _db.Teachers.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            //var teachers = _db.Teachers.ToList();
            ViewData["CurrentFilter"] = searchString;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (!String.IsNullOrEmpty(searchString))
            {
                teachers = teachers.Where(x => x.teacherSurname.Contains(searchString) || x.teacherName.Contains(searchString)).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    teachers = teachers.OrderByDescending(s => s.teacherName).ToList();
                    break;
                case "Date":
                    teachers = teachers.OrderBy(s => s.teacherDob).ToList();
                    break;
                case "date_desc":
                    teachers = teachers.OrderByDescending(s => s.teacherDob).ToList();
                    break;
                default:
                    teachers = teachers.OrderBy(s => s.teacherName).ToList();
                    break;
            }
            return View(teachers);
        }

        [HttpPost]
        public ActionResult Index(FormCollection formCollection)
        {
            var file = Request.Form.Files["fileToImport"];

            if (file == null)
            {
                ViewBag.Result = "File is missing";
                return View();
            }

            return View(); ;
        }

        //private List<string> SaveTeachersToDb(List<Teachers> model, List<string> errors)
        //{
        //    try
        //    {
        //        _db.Teachers.Add();
        //        _db.SaveChanges();
        //    }
        //    catch (Exception ex)
        //    {
        //        errors.Add("Errors inserting employees : " + ex.Message);
        //    }
        //    return errors;
        //}

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Teachers teachers)
        {
            if (ModelState.IsValid)
            {
                _db.Teachers.Add(teachers);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teachers);
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            var objToEdit = _db.Teachers.Find(id);
            if (objToEdit == null)
            {
                return NotFound();
            }
            return View(objToEdit);
        }

        [HttpPost]
        public IActionResult EditTeacher(Teachers teachers)
        {
            if (teachers == null)
            {
                return NotFound();
            }
            _db.Teachers.Update(teachers);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var objToDelete = _db.Teachers.Find(id);

            if (objToDelete == null)
            {
                return NotFound();
            }

            _db.Teachers.Remove(objToDelete);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CRUD_School294/Views/Teachers/Create.cshtml
@model CRUD_School294.Models.Teachers

@{ 
    ViewData["Title"] = "New Teacher";
}

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Teacher Registration</h2>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group row">
                    <div class="col">
                        <label asp-for="teacherSurname"></label>
                    </div>
                    <div class="col">
                        <label asp-for="teacherName"></label>
                    </div>
                    <div class="col">
                        <label asp-for="teacherDob"></label>
                    </div>
                    <div class="col">
                        <label asp-for="teacherContacts"></label>
                    </div>
                    <div class="col">
                        <label asp-for="studentContact2"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input asp-for="teacherSurname" class="form-control">
                        @*<span asp-validation-for="studentSurname" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="teacherName" class="form-control">
                        @*<span asp-validation-for="studentName" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="teacherDob" class="form-control">
                        @*<span asp-validation-for="studentDob" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="teacherContacts" class="form-control">
                        @*<span asp-validation-for="studentClass" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="studentContact2" class="form-control">
                        @*<span asp-validation-for="studentContacts" class="text-danger"></span>*@
                    </div>
                </div>
                <div class="form-group row text-right">
                    <div class="col-8 offset-2 row pt-5">
                        <div class="col">
                            <input type="submit" class="btn btn-success w-50" value="Register">
                        </div>
                        <div class="col">
                            <a class="btn btn-info w-50" asp-controller="Students" asp-action="Index">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CRUD_School294/Views/Teachers/Edit.cshtml
@model CRUD_School294.Models.Teachers

@{ 
    ViewData["Title"] = "Edit Teacher";
}

<form method="post" asp-action="EditTeacher">
    <input asp-for="teacherId" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Teacher Edit</h2>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group row">
                    <div class="col">
                        <label asp-for="teacherSurname"></label>
                    </div>
                    <div class="col">
                        <label asp-for="teacherName"></label>
                    </div>
                    <div class="col">
                        <label asp-for="teacherDob"></label>
                    </div>
                    <div class="col">
                        <label asp-for="teacherContacts"></label>
                    </div>
                    <div class="col">
                        <label asp-for="studentContact2"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input asp-for="teacherSurname" class="form-control">
                        @*<span asp-validation-for="studentSurname" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="teacherName" class="form-control">
                        @*<span asp-validation-for="studentName" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="teacherDob" class="form-control">
                        @*<span asp-validation-for="studentDob" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="teacherContacts" class="form-control">
                        @*<span asp-validation-for="studentClass" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input asp-for="studentContact2" class="form-control">
                        @*<span asp-validation-for="studentContacts" class="text-danger"></span>*@
                    </div>
                </div>
                <div class="form-group row text-right">
                    <div class="col-8 offset-2 row pt-5">
                        <div class="col">
                            <input type="submit" class="btn btn-success w-50" value="Save">
                        </div>
                        <div class="col">
                            <a class="btn btn-info w-50" asp-controller="Teachers" asp-action="Index">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CRUD_School294/Views/Teachers/Index.cshtml
@model IEnumerable<CRUD_School294.Models.Teachers>

@{
    ViewData["Title"] = "All Teachers";
    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}



<div class="container p-3">
    <div class="col-md-5">
        <form method="post" enctype="multipart/form-data" asp-controller="Teachers" asp-action="Index">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload file</p>
                    <input class="form-control" name="fileToImport" id="fileToImport" type="file" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <input class="btn btn-success" type="submit" value="Upload" />
                </div>
            </div>
        </form>
    </div>
    <div class="row pt-4">
        <div class="col-2">
            <h2 class="text-dark">Teachers</h2>
        </div>
        <div class="col-10 text-right">
            <form asp-action="Index" method="get">
                <div class="form-actions no-color">
                    <p>
                        Search by Name & Surname (case sensitive): <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                        <input type="submit" value="Search" class="btn btn-primary" /> &nbsp;&nbsp;
                        <a asp-action="Index" class="btn btn-warning">Refresh list</a>
                        <a class="btn btn-success" asp-controller="Teachers" asp-action="Create">Add Teacher</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
    <partial name="_pager" model="@pager" />
    </br>

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Surname
                    </th>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">Name</a>
                    </th>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]">Date of Birth</a>
                    </th>
                    <th>
                        Contacts
                    </th>
                    <th>
                        Contacts 2
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="14%">@item.teacherSurname</td>
                        <td width="14%">@item.teacherName</td>
                        <td width="14%">@item.teacherDob.ToShortDateString()</td>
                        <td width="14%">@item.teacherContacts</td>
                        <td width="14%">@item.studentContact2</td>
                        <td width="30%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="Teachers" asp-action="Edit" asp-route-id="@item.teacherId" class="btn btn-warning mx-1">Update</a>
                                <a onclick="return confirm('Are you sure you want to delete a teacher?');" asp-controller="Teachers" asp-action="Delete" asp-route-id="@item.teacherId" class="btn btn-danger">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items to show</p>
    }

    <partial name="_pager" model="@pager" />


</div>